add list users API endpoint
UnosquareBelfast/CVGenerator-backend pull request #4
Opened 2019-11-01 14:34 UTC by pbisby-uno

- add list users API endpoint.
- add necessary entity, DTO, View and Service.
- add unit and integration tests.

2019-11-04 17:00 UTC, escullion approved these changes
Looks good - just one query about mapperutil, the rest are code style questions

2019-11-04 17:00 UTC, escullion commented on src/integTest/java/com/unosquare/cvgenerator/controller/UserControllerTest.java
> +public class UserControllerTest extends AbstractWebIntegrationTest {
Any thoughts on naming scheme for unit vs integration tests? Maybe name this `UserControllerIntegrationTest`, then regular unit tests can be `XyzTest`?

2019-11-04 17:00 UTC, escullion commented on src/main/java/com/unosquare/cvgenerator/configuration/MapperConfig.java
> +    public MapperUtil mapperUtil() { return new MapperUtil(new ModelMapper()); }
I think its worth using ModelMapper instead of MapperUtil - will need a configuration for modelmapper later to set up custom mappings/converters

2019-11-04 17:00 UTC, escullion commented on src/main/java/com/unosquare/cvgenerator/controller/UserController.java
> +    @CrossOrigin
Like you've mentioned - we can create a global cors config

2019-11-04 17:00 UTC, escullion commented on src/main/java/com/unosquare/cvgenerator/controller/UserController.java
> +    @GetMapping("/users")
naming convention for mappings - don't need `/` at the start,

2019-11-04 17:00 UTC, escullion commented on src/main/java/com/unosquare/cvgenerator/service/UserServiceImpl.java
> +        return mapperUtil.mapAll(result, UserDTO.class);
Rather than having a separate util class for mapping, not pretty but we can use something like:
```
List<PostDTO> entityToDto = modelMapper.map(postEntity, new TypeToken<List<PostDTO>>(){}.getType());
```

@BrownMark curious to get your thoughts, how you usually manage converting lists?

2019-11-04 17:00 UTC, escullion commented on src/test/java/com/unosquare/cvgenerator/service/UserServiceImplTest.java
> +        testListUser.add(user1);
Can simplify to `List<User> testListUser = Arrays.asList(user1, user2);`

2019-11-06 10:35 UTC, BrownMark requested changes

2019-11-06 10:35 UTC, BrownMark commented on src/main/java/com/unosquare/cvgenerator/controller/UserController.java
> +    @GetMapping("/users")
If every endpoint starts with users/  does it make sense to have to controller at the users/ route?

2019-11-06 10:35 UTC, BrownMark commented on src/main/java/com/unosquare/cvgenerator/service/UserServiceImpl.java
> +        return mapperUtil.mapAll(result, UserDTO.class);
honestly, normally we do the same thing and add a specific method to handle the list mappings.

Just keeps things a bit cleaner inline. 

We do normally maintain the same .map naming though.

2019-11-06 10:35 UTC, BrownMark commented on src/test/java/com/unosquare/cvgenerator/service/UserServiceImplTest.java
> +        testListUser.add(user1);
JFixture can be very handy for mocked data too.

2019-11-06 10:35 UTC, BrownMark commented on src/main/java/com/unosquare/cvgenerator/configuration/MapperConfig.java
> +    public MapperUtil mapperUtil() { return new MapperUtil(new ModelMapper()); }
We have a pretty good approach used on other projects for managing configurations for modelmapper. Give me a shout when you're looking at this @pbisby-uno

2019-11-07 12:42 UTC, BrownMark approved these changes

2019-11-07 14:23 UTC, merged